### ISSUE TITLE
Could you please give me a copy of this dataset？ 

### ISSUE THREAD

**Issue by zhangFROST** [saviola777/fhdo-imageclef2020-coral#1]
Excuse me， I am a researcher doing  research about coral ,but now the official website of this match has closed the data download window .Could you please give me a copy of the dataset？ 
here is my email :unlimitedzhang@gmail.com

**Comment by saviola777** [comment]
Hello, unfortunately this is a licensed dataset that we are not able to share, you will have to contact the challenge organizers.
